stages:
  # Satge 01: Data Ingestion 
  data_ingestion:
    cmd: python src/insurance_premium_prediction/pipeline/data_ingestion.py
    deps:
      - src/insurance_premium_prediction/pipeline/data_ingestion.py
      - config/secrect.yaml
      - config/config.yaml
    outs:
      - artifacts/data/data.csv
  
  # Stage 02: Data Preprocessing
  data_preprocessing:
    cmd: python src/insurance_premium_prediction/pipeline/data_preprocessing.py
    deps:
      - src/insurance_premium_prediction/pipeline/data_preprocessing.py
      - config/secrect.yaml
      - config/config.yaml
    outs:
      - artifacts/processed_data/encoded_metrics.json
      - artifacts/processed_data/train.csv
      - artifacts/processed_data/test.csv