stages:
  # Satge 01: Data Ingestion 
  data_ingestion:
    cmd: python src/insurance_premium_prediction/pipeline/data_ingestion.py
    deps:
      - src/insurance_premium_prediction/pipeline/data_ingestion.py
      - config/secrect.yaml
      - config/config.yaml
    outs:
      - artifacts/data/data.csv