RandomForestRegressorParams:
  bootstrap: True
  max_depth: 5
  max_features: 5
  min_samples_leaf: 3
  min_samples_split: 5
  n_estimators: 400
  random_state: 13


GradientBoostingRegressor:
  n_estimators: 600
  learning_rate: 0.01
  max_depth: 5
  random_state: 13
  subsample: 0.41
